### ISSUE TITLE
Einstiegstool Sample YAML file

### ISSUE THREAD

**Issue by derFint** [WolfgangFahl/dcm#56]
`Sample` for Einstiegstool questions addressing two competence facets of the GRETA competence model. These questions can be used for the self assessment element of the dcm. 

```yaml
competences:
- competence_title: "Lerninhalte und -ziele"
  competence_id: "https://www.greta-die.de/webpages/kompetenzfacetten-index/kf1-lerninhalte-und-ziele-1"
  task: "Zunächst geht es um die Bestimmung von Lerninhalten und -zielen für das anstehende Lehr-Lern-Angebot. Welche der Aussagen treffen für Sie zu?"
  questions:
  - question: 1 
    text: "Ich kenne Lernzieltaxonomien und Grundlagen für die Formulierung von Lernzielen und Lerninhalten."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 2 
    text: "Ich bin es gewohnt, für meine Lernangebote entsprechende Lerninhalte und -ziele zu formulieren."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 3
    text: "Ich bin erfahren darin, die formulierten Lerninhalte und -ziele kritisch zu beurteilen und zu erkennen, ob sie für die Teilnehmenden angemessen sind."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 4 
    text: "Ich bin geübt darin, Lernziele teilnehmerspezifisch der jeweiligen Situation anzupassen und weiterzuentwickeln und die Lerninhalte darauf abzustimmen."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
- competence_title: "Methoden, Medien und Lernmaterialien"
  competence_id: "https://www.greta-die.de/webpages/kompetenzfacetten-index/kompetenzfacette-methoden-medien-und-lernmaterialien"
  task: "Schätzen Sie sich selbst in Bezug auf den Einsatz von Methoden, Medien und Lernmaterialien in Ihren Weiterbildungsangeboten ein!"
  questions:
  - question: 1 
    text: "Ich habe hinreichende Kenntnisse, um Methoden, Medien und Lernmaterialien zielgerecht auszuwählen und zu gestalten."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 2 
    text: "Ich bin erfahren darin, Methoden, Medien und Lermaterialien situationsgerecht einzusetzen und an den Bedarfen und Lernfortschritten der Teilnehmenden auszurichten."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 3
    text: "Ich bin es gewohnt, die Eignung der eingesetzten Methoden, Medien und Lernmaterialien im Lehr-Lernprozess zu hinterfragen und deren Einsatz spontan anzupassen."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
  - question: 4 
    text: "Ich verfüge über Strategien, um Weiterbildungsangebote je Thema und Teilnehmende immer wieder neu mit unterschiedlichen Kombinationen an Methoden, Medien und Lernmaterialien zu planen und umzusetzen."
    answers:
      - option: 1
        text: "trifft nicht zu"
      - option: 2
        text: "trifft eher nicht zu"
      - option: 3
        text: "trifft eher zu"
      - option: 4
        text: "trifft voll zu"
```
